kotlin.code.style=official
org.gradle.parallel=true
group=dev.failgood
version=0.9.2

# Project metadata (still used by publishing)
project.name=FailGood
project.description=a fast test runner for kotlin
project.url=https://github.com/failgood/failgood
project.repo=failgood/failgood

kotlin.build.report.output=file

# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
# disabled because nexus publishing does not work, with it, and I'm a bit tired of gradle research.
# org.gradle.configuration-cache = true

# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
# also disabling because it leads to super weird bugs that I have no interest in tracking down.
#org.gradle.caching = true

# Enable Gradle Kotlin DSL Lazy Property Assignment -> https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:assignment
#systemProp.org.gradle.unsafe.kotlin.assignment = true # default since gradle 8.2

# Example local iOS app-test config:
# ./gradlew :failgood:iosAppTest
# failgood.ios.testDevice=Sturm devel
# failgood.ios.bundleIdentifier=com.example.failgood.tests
# failgood.ios.provisioningProfile=/Users/you/Library/Developer/Xcode/UserData/Provisioning Profiles/example.mobileprovision
# failgood.ios.signingIdentity=63E970A45EC20B91C11992FAB36A9B54C4E37274
