name: PIT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    name: Pitest on jdk 19
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        env:
          CI: true
          PITEST_THREADS: 2
          FAILGOOD_WATCHDOG_MILLIS: 100000
        run: ./gradlew pitest
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-reports-pitest
          path: failgood/build/reports
