name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11, 17 ]
        experimental: [ false ]
# Failgood works and builds great on windows, but CI is very flaky
# feel free to submit a PR that fixes CI on windows if you need this
#        include:
#          - os: windows-latest
#            java: 17
#            experimental: true

    name: Tests on ${{ matrix.os }} with JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        env:
          CI: true
          SLOW_CI: true
          FAILGOOD_WATCHDOG_MILLIS: 100000
        run: ./gradlew check build koverXmlReport
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-reports-${{ matrix.os }}-${{ matrix.java }}
          path: failgood/build/reports
      - uses: codecov/codecov-action@v4
        with:
          #        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: failgood/build/reports/kover/xml/report.xml
          #        flags: unittests # optional
          #        name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
